= SDL Platform

== Internet resources

Handmade Penguin - companion to Casey Muratori's amazing Handmade Hero series, for Linux.
https://davidgow.net/handmadepenguin/default.html

== TODO

=== Add sound

These chapters from Handmade Penguing is exactly what I need:
https://davidgow.net/handmadepenguin/ch7.html
https://davidgow.net/handmadepenguin/ch8.html
https://davidgow.net/handmadepenguin/ch9.html
https://davidgow.net/handmadepenguin/ch12.html
https://davidgow.net/handmadepenguin/ch19.html

First goal: output a sine wave.

https://wiki.libsdl.org/SDL2/CategoryAudio
https://github.com/jakebesworth/Simple-SDL2-Audio/blob/master/src/audio.c

https://wiki.libsdl.org/SDL2/SDL_OpenAudioDevice
https://wiki.libsdl.org/SDL2/SDL_AudioFormat
https://wiki.libsdl.org/SDL2/SDL_PauseAudioDevice
https://wiki.libsdl.org/SDL2/SDL_CloseAudioDevice
https://github.com/MasterQ32/SDL.zig/blob/fbe5f599c65b7a5642990443b2a686d1c53a4985/src/wrapper/sdl.zig#L2573
https://wiki.libsdl.org/SDL2/SDL_MixAudioFormat

Which approach is better - SDL_QueueAudio or SDL_AudioSpec.callback?
https://wiki.libsdl.org/SDL2/SDL_AudioSpec
https://wiki.libsdl.org/SDL2/SDL_QueueAudio

Watch the Handmade Hero episodes about sound.

=== Try to use https://github.com/SpexGuy/Zig-ImGui

== DONE

=== Fix the example application on NixOS

....
/home/reinis/dev/learn/zig/zig_sdl_platform/zig-out/bin/example: /nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /nix/store/yaz7pyf0ah88g2v505l38n0f3wg2vzdj-glibc-2.37-8/lib/libpthread.so.0)
/home/reinis/dev/learn/zig/zig_sdl_platform/zig-out/bin/example: /nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /nix/store/yaz7pyf0ah88g2v505l38n0f3wg2vzdj-glibc-2.37-8/lib/librt.so.1)
/home/reinis/dev/learn/zig/zig_sdl_platform/zig-out/bin/example: /nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/0d4xl0xk1g0w41yqyd64jvzbip5lhfig-libXdmcp-1.1.3/lib/libXdmcp.so.6)
....

This could be related:
https://github.com/NixOS/nixpkgs/issues/228899

Checked that the application builds and runs OK on non-NixOS.

A bug has been registered against Zig:
https://github.com/ziglang/zig/issues/15898

For now I will use nixpkgs 22.11 (same as my NixOS config) as a workaround.

